### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by Sweatys** [jcwml/CSGO-Trigger-Bot-2#1]
how to run it

**Comment by jcwml** [comment]
You are on Linux? You need to compile the program and execute it, that is all. Execute `release.sh` and it will compile and execute the program, from there follow the instructions for the appropriate hotkeys to enable/disable the bot.

You may need to install these dependencies first:
`sudo apt install clang espeak libx11-dev`

**Comment by Sweatys** [comment]
unfortunately I use windows what should I do?(

**Comment by jcwml** [comment]
You can boot Ubuntu Linux off a USB stick for now, but eventually you might want to consider installing it on a second SATA or M.2 drive inside your computer.

Follow these instructions setting up Ubuntu Linux on a bootable USB drive:
https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview
